### ISSUE TITLE
Error for live stream

### ISSUE THREAD

**Issue by PanderMusubi** [DamonToumbourou/plugin.video.c31#1]
When playing the live stream in Kodi 15.2 and 16.1, an error occurs and the log says:

```
...
23:19:25 T:140542117664512  NOTICE: [xbmcswift2] Request for "/live_stream/" matches rule for function "live_stream"
23:19:25 T:140542117664512 WARNING: [xbmcswift2] {'path': 'http://c31.mediafoundry.com.au/sites/default/files/manifest/manifest_live_27.m3u8', 'info_type': 'video', 'label': 'C31 Live'}
23:19:25 T:140542117664512 WARNING: [xbmcswift2] <type 'dict'>
23:19:25 T:140542117664512 WARNING: [xbmcswift2] [<ListItem 'C31 Live'>]
23:19:25 T:140542117664512 WARNING: [xbmcswift2] <type 'list'>
23:19:25 T:140542117664512   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                         - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                        Error Type: <type 'exceptions.AttributeError'>
                                        Error Contents: 'list' object has no attribute 'keys'
                                        Traceback (most recent call last):
                                          File "/home/pander/.kodi/addons/plugin.video.c31/addon.py", line 174, in <module>
                                            plugin.run()
                                          File "/home/pander/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 340, in run
                                            items = self._dispatch(self.request.path)
                                          File "/home/pander/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 323, in _dispatch
                                            listitems = self.finish(listitems)
                                          File "/home/pander/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 495, in finish
                                            self.add_items(items)
                                          File "/home/pander/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 411, in add_items
                                            _items = [self._listitemify(item) for item in items]
                                          File "/home/pander/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py", line 314, in _listitemify
                                            if 'info_type' not in item.keys():
                                        AttributeError: 'list' object has no attribute 'keys'
                                        -->End of Python script error report<--
...
23:19:32 T:140543713225024   ERROR: GetDirectory - Error getting plugin://plugin.video.c31/live_stream/
23:19:32 T:140543713225024   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.c31/live_stream/) failed
```

For debugging purposes, Iadded these two warning log entries in `~/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/xbmcmixin.py`

```
    # Create ListItems for anything that is not already an instance of
    # ListItem
    log.warning(item)
    log.warning(type(item))
    if not hasattr(item, 'as_tuple'):
        if 'info_type' not in item.keys():
            item['info_type'] = info_type
        item = xbmcswift2.ListItem.from_dict(**item)
    return item
```

How can this be fixed?

**Comment by PanderMusubi** [comment]
I suggest to check if type is dict before making a call to xbmcswift2. Do you have any ideas to fix it in a proper way?

**Comment by PanderMusubi** [comment]
Better refactor the code to use https://github.com/Sinap/kodiswift

**Comment by DamonToumbourou** [comment]
Thank you,
I have exams at the moment and no spare time and will look at it after exam period.

**Comment by PanderMusubi** [comment]
I am looking into refactoring to kodiswift.
